### ISSUE TITLE
Brace dependecy

### ISSUE THREAD

**Issue by jpsc** [micromatch/expand-braces#1]
Trying to update the dependency of brace to 1.8 but got some tests failing that seems related to how brace is actually handling things differently.
Should this be a no go for updating to 1.x or should be change tests ?

I got here because I was getting some warning's of outdated use of lodash from brace 0.x.

Cheers.

**Comment by jonschlinkert** [comment]
Can you paste in the error so I can take a look? It might just be that braces needs to be updated. Also I haven't used lodash in ages, it would be good to know where that error originates so I can fix it.  thanks

**Comment by jpsc** [comment]
This is test error output when I run tests after updating braces to 1.8.2.

``` bash
given an array of patterns with braces
    braces
      ✓ should work with a list of strings
      ✓ should work with arrays of strings
      ✓ should work with no braces
      ✓ should uniquify the result.
      ✓ should work with one value
      ✓ should work with nested non-sets
      ✓ should work with commas.
      ✓ should expand sets
      1) should throw an error when imbalanced braces are found.
    range expansion
      ✓ should expand numerical ranges
      ✓ should honor padding
      ✓ should expand alphabetical ranges
      2) should use a custom function for expansions.
      3) should use a custom function for expansions.
    should expand a combination of nested sets and ranges.
      ✓ should expand sets


  12 passing (19ms)
  3 failing

  1) given an array of patterns with braces braces should throw an error when imbalanced braces are found.:
     AssertionError: expected [Function] to throw exception
      at Proxy.Assertion.fail (node_modules/should/lib/assertion.js:228:17)
      at Proxy.prop.(anonymous function) (node_modules/should/lib/assertion.js:69:14)
      at Context.<anonymous> (test.js:50:22)

  2) given an array of patterns with braces range expansion should use a custom function for expansions.:

      AssertionError: expected [ '97', '99', '101', '103', '105', '107', '109', '111' ] to equal [ 'a0', 'b1', 'c2', 'd3', 'e4', 'f5', 'g6', 'h7' ] (at '0', A has '97' and B has 'a0')
      + expected - actual

       [
      -  "97"
      -  "99"
      -  "101"
      -  "103"
      -  "105"
      -  "107"
      -  "109"
      -  "111"
      +  "a0"
      +  "b1"
      +  "c2"
      +  "d3"
      +  "e4"
      +  "f5"
      +  "g6"
      +  "h7"
       ]

      at Proxy.Assertion.fail (node_modules/should/lib/assertion.js:228:17)
      at Proxy.prop.(anonymous function) (node_modules/should/lib/assertion.js:69:14)
      at Context.<anonymous> (test.js:72:20)

  3) given an array of patterns with braces range expansion should use a custom function for expansions.:

      AssertionError: expected [ '_97', '_98', '_99', '_100', '_101', '_102', '_103', '_104' ] to equal [ '_a', '_b', '_c', '_d', '_e', '_f', '_g', '_h' ] (at '0', A has '_97' and B has '_a')
      + expected - actual

       [
      -  "_97"
      -  "_98"
      -  "_99"
      -  "_100"
      -  "_101"
      -  "_102"
      -  "_103"
      -  "_104"
      +  "_a"
      +  "_b"
      +  "_c"
      +  "_d"
      +  "_e"
      +  "_f"
      +  "_g"
      +  "_h"
       ]

      at Proxy.Assertion.fail (node_modules/should/lib/assertion.js:228:17)
      at Proxy.prop.(anonymous function) (node_modules/should/lib/assertion.js:69:14)
      at Context.<anonymous> (test.js:79:20)

```

**Comment by jonschlinkert** [comment]
ok thanks for the extra info. I believe that will be fixed by the latest version. I'll try to get to this today, if not this weekend.

**Comment by jonschlinkert** [comment]
Haven't forgotten about this. I worked on related libs this weekend. I'll get this fixed asap

**Comment by jpsc** [comment]
Thanks for the update. It's not that you own me anything. I'm grateful for such short answers. Keep the great work.

**Comment by jonschlinkert** [comment]
closing in favor of https://github.com/micromatch/expand-braces/pull/2
